name: Build
on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize]
jobs:
  lint:
    name: Build package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build
